### ISSUE TITLE
hi can i ask u question :)

### ISSUE THREAD

**Issue by mariah1772** [mariah1772/final-assignment-mariah1772#2]
I am doing my HTML portfolio and I would like to have a hovering mouse and also searched a lot I couldn't find out how I can do this small animation could you please give me some hints to understand how to do it? i will put the URL  my WordPress portfolio (I want to hover by mouse like this when hovering is like small text).

http://www.mariahamidizadeh.com/minimal-home/

if you go by mouse on images you can see what I mean:)
I want to do it for my work page.
 I'm looking forward to your reply :)

**Comment by gorazd** [comment]
Hello, apologies for responding to you only now.

There is an elegant solution to achieve this by only using HTML and CSS.

Basically what you could do is create a `link` containing the `image` and the text.
Next you hide the text with f.ex. the `opacity` property. Then you use a CSS selector to target the text inside the hovered link, and show it. Last you add the `transition` property to add the fade animation.

Example HTML
```html
<a href="#" class="work-link">
  <img src...>
  <p class="work-link-description">Text to show</p>
</a>
```
Example CSS
```css
.work-link-description {
  opacity: 0;
  transform: translateY(20px);

  transition: all 50ms ease-in;
}
/* when the mouse is over the link, modify the description inside the link */ 
.work-link:hover .work-link-description {
  opacity: 1;
  transform: translateY(0);
}
```
Please let me know if this makes sense. I can prepare a small demo for you otherwise.
